---
title: "Research"
---

$$\\[2pt]$$

### Working Papers

$$\\[0.5pt]$$

#### Neighborhood Effects on the Production of Human Capital: Evidence from Movers in North Carolina
[[PDF]](content/dowling_NCneighborhoods.pdf)

**Abstract:** I investigate whether neighborhood exposures during childhood affect academic outcomes observed at the end-of-high school, and whether the effects can be explained by neighborhood schools. I find that neighborhood exposures during childhood affect high-stakes standardized exam scores, 12th grade GPA, the probability of intending to attend college and the probability of dropping out of high school. By leveraging variation in the age at which students move, I estimate exposure effects that encompass the effect of neighborhood schools and other amenities. I demonstrate that these effects can not be fully explained by conventional school quality measures based on test scores or graduation rates, which points to the potential importance of peer effects and other neighborhood amenities as complementary mechanisms. 

***

$$\\[0.5pt]$$

### Work in Progress

$$\\[1pt]$$

#### Tax Subsidies and the Cost of Homeownership: Evidence from the Tax Cuts and Jobs Act
*Joint with Kelly Bishop, Nicolai Kuminoff and Alvin Murphy.*

**Abstract:** Homeownership in the U.S. has been supported via the mortgage-interest-deduction provision of the tax code. For example, during 2017, U.S. tax policy effectively subsidized homeownership by approximately $90 billion. However, U.S. tax policy was substantially changed with the Tax Cuts and Jobs Act (TCJA) of 2017, which, by doubling the standard deduction, effectively made housing more expensive relative to other types of consumption by reducing the incentive to claim mortgage interest as a deductible expense. This paper quantifies the magnitude of the subsidization of homeownership and calculates how the TCJA affected both this subsidization and homeownership costs more broadly.

***

$$\\[2pt]$$